development:
  database: listing_development
  adapter: postgresql
  username: postgres
  password: password
  host: localhost
  port: 5432

production:
  database: listing_prod
  adapter: postgresql
  username: postgres
  password: password
  host: localhost
  port: 5432

test:
  database: listing_test
  adapter: postgresql
  username: postgres
  password: password
  host: localhost
  port: 5432
